### ISSUE TITLE
oracle jdk8 281 Caused by: java.lang.ClassFormatError

### ISSUE THREAD

**Issue by ddatsh** [alibaba/testable-mock#117]
和 #112 类似

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.xx.order</groupId>
    <artifactId>order-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.9.RELEASE</version>
    </parent>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <lombok.version>1.18.16</lombok.version>
        <testable.version>0.5.2</testable.version>
        <jacoco.version>0.8.5</jacoco.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>com.alibaba.testable</groupId>
                <artifactId>testable-all</artifactId>
                <version>${testable.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.testable</groupId>
            <artifactId>testable-all</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>@{argLine}
                        -javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar=mockScope=associated
                    </argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <includeSystemScope>true</includeSystemScope>
                    <layers>
                        <enabled>true</enabled>
                    </layers>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <configuration>
                    <includes>
                        <include>com/**/*</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>pre-test</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>post-test</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

```java

import org.springframework.stereotype.*;

import javax.annotation.*;

@Service
public class AService {

	@Resource
	BService bService;

}
```
```java

import org.springframework.stereotype.*;

@Service
public class BService {

	public String b() {

		return "b";
	}
}
```

```java
import com.alibaba.testable.core.annotation.*;
import com.alibaba.testable.core.util.*;
import org.junit.jupiter.api.*;

public class AServiceTest {

	public static class Mock {

		@MockMethod(targetClass = BService.class)
		public String b() {

			// 这个 boolean 去了就不报错
			boolean flag = false;
			String  b            = null;
			switch ((String) MockContextUtil.parameters()
			                                .getOrDefault("contractBind", "")) {
				case "true":

					break;
			}
			return b;

		}

	}

	@Test
	public void test() {

	}

}
```

idea 里去跑测试，会报ClassFormatError错，但在 mvn test ，它这个测试类就不会显示有被执行

在 switch里加上个没用到的 boolean就报错

**Comment by linfan** [comment]
我试着创建了一个空的工程，加上上述代码，在 IntelliJ 2020.3.2 版本下做了验证，但没能复现出异常。
[testable-issue117.zip](https://github.com/alibaba/testable-mock/files/6138954/testable-issue117.zip)

能贴一下`ClassFormatError`错误后面的详细报错信息吗？或者如果能提供一个通过`dumpPath`参数导出的报错情况时的`AServiceTest_Mock.class`文件更佳。

**Comment by ddatsh** [comment]
> 我试着创建了一个空的工程，加上上述代码，在 IntelliJ 2020.3.2 版本下做了验证，但没能复现出异常。
> [testable-issue117.zip](https://github.com/alibaba/testable-mock/files/6138954/testable-issue117.zip)
> 
> 能贴一下`ClassFormatError`错误后面的详细报错信息吗？或者如果能提供一个通过`dumpPath`参数导出的报错情况时的`AServiceTest_Mock.class`文件更佳。

是  oracle  8 281?

**Comment by ddatsh** [comment]
```java
Internal Error occurred.
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:189)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'com.shanghaionstar.order.service.order.AServiceTest'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:45)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:181)
	... 6 more
Caused by: java.lang.ClassFormatError: Illegal class name "Lcom/shanghaionstar/order/service/order/BService;" in class file com/shanghaionstar/order/service/order/AServiceTest$Mock
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredClasses0(Native Method)
	at java.lang.Class.getDeclaredClasses(Class.java:1867)
	at org.junit.platform.commons.util.ReflectionUtils.findNestedClasses(ReflectionUtils.java:1022)
	at org.junit.platform.commons.util.ReflectionUtils.findNestedClasses(ReflectionUtils.java:1007)
	at org.junit.platform.commons.support.ReflectionSupport.findNestedClasses(ReflectionSupport.java:333)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$toResolution$12(ClassSelectorResolver.java:138)
	at org.junit.platform.engine.support.discovery.SelectorResolver$Match.expand(SelectorResolver.java:646)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$enqueueAdditionalSelectors$1(EngineDiscoveryRequestResolution.java:109)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Collections$2.tryAdvance(Collections.java:4719)
	at java.util.Collections$2.forEachRemaining(Collections.java:4727)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.enqueueAdditionalSelectors(EngineDiscoveryRequestResolution.java:108)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:94)
	... 11 more
```

**Comment by linfan** [comment]
复现了，确实是类似是原因。

加上一行`boolean flag`变量就触发是因为恰好这行代码会使`switch`跳转前后的堆栈深度差>3，导致使用了`FRAME FULL`字节码（深度差少于3的时候使用`FRAME APPEND`）。TestableMock对`FRAME FULL`字节码的处理存在与`CHECKCAST`类似的问题，导致在较高版本JVM下出现异常。这个复现条件还是比较苛刻的，一般不太容易触发到，同样感谢你提供的实例代码。

会在下次发布的时候包含修复。
