### ISSUE TITLE
添加参数jvmArgs后gradle编译错误

### ISSUE THREAD

**Issue by Ares745** [alibaba/testable-mock#130]
当我在 gradle  test{ }内添加 参数jvmArgs后，启动单元测试报错：serialVersionUID不一致  且找不到测试类
麻烦帮忙查看一下

错误如下：

org.gradle.api.UncheckedIOException: java.io.InvalidClassException: org.gradle.process.internal.worker.child.ActionExecutionWorker; local class incompatible: stream classdesc serialVersionUID = -502578137267031059, local class serialVersionUID = -7831017032782868858
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:123)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:68)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:73)
Caused by: java.io.InvalidClassException: org.gradle.process.internal.worker.child.ActionExecutionWorker; local class incompatible: stream classdesc serialVersionUID = -502578137267031059, local class serialVersionUID = -7831017032782868858
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:121)
	... 3 more
> Task :test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [controller.MockTest.testttt](filter.includeTestsMatching)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

**Comment by linfan** [comment]
使用的版本是`0.6.2`吗？

**Comment by heyzqq** [comment]
我用的是 0.6.0，Spring boot 2.4.4，Test 也是报错：

gradle 配置：

```
plugins {
    id 'org.springframework.boot' version '2.4.4'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // TestableMock
    testImplementation('com.alibaba.testable:testable-all:0.6.0')
    testAnnotationProcessor('com.alibaba.testable:testable-processor:0.6.0')
}

test {
    jvmArgs "-javaagent:${classpath.find { it.name.contains("testable-agent") }.absolutePath}"
    useJUnitPlatform()
}
```

错误信息：
```
> Task :app:compileJava
> Task :app:processResources NO-SOURCE
> Task :app:classes
> Task :app:compileTestJava
[INFO] Testable processor initialized
> Task :app:processTestResources NO-SOURCE
> Task :app:testClasses
> Task :app:test FAILED
java.lang.NoClassDefFoundError: javax/lang/model/type/NullType
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	at java.base/java.net.InetAddress.loadImpl(InetAddress.java:1684)
	at java.base/java.net.InetAddressImplFactory.create(InetAddress.java:1773)
	at java.base/java.net.InetAddress.<clinit>(InetAddress.java:1132)
	at org.gradle.internal.remote.internal.inet.MultiChoiceAddressSerializer.read(MultiChoiceAddressSerializer.java:37)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:101)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:test'.
> Process 'Gradle Test Executor 9' finished with non-zero exit value 1
```

**Comment by Ares745** [comment]
> 使用的版本是`0.6.2`吗？

之前是0.6.0 在我更换版本0.6.2 后该问题已经解决了。
感觉 OmniConstructor 很有用，但是 它在 `GRPC参数构建和某些pojo初始化有空指针问题：

错误信息：
`com.alibaba.testable.core.exception.ClassConstructionException: Failed to invoke constructor
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:66)
	at com.alibaba.testable.core.tool.OmniConstructor.createInstance(OmniConstructor.java:190)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:78)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:60)
	at com.alibaba.testable.core.tool.OmniConstructor.createInstance(OmniConstructor.java:190)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:78)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:60)
	at com.alibaba.testable.core.tool.OmniConstructor.createInstance(OmniConstructor.java:190)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:78)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:60)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:84)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:60)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:84)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:60)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:29)
	at com.xiaoju.didipay.api.service.PixServiceTest.test_decodeStaticQRCode(ServiceTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)
`

**Comment by linfan** [comment]
`0.6.0`与`Gradle`构建存在部分不兼容问题，在`0.6.1`及之后版本中已修复，但对`OmniConstructor`的功能稍有影响。
预计会在`0.6.3`版本里提供一种比较完美的解决方案，后续会在此Issue中同步进展~

**Comment by linfan** [comment]
`0.6.3`版本已发布，可以通过开启OmniConstructor的字节码增强模式来解决。

在项目的`src/test/resources`目录创建一个`testable.properties`文件，写入以下内容即可：

```
omni.constructor.enhance.enable = true
```

具体可参考[全局运行参数](http://freyrlin.gitee.io/testable-mock/#/zh-cn/doc/javaagent-args)文档。
