### ISSUE TITLE
0.6.2 在 SpringBoot 项目中，执行测试失败，改为 0.5.2 则没问题

### ISSUE THREAD

**Issue by heyzqq** [alibaba/testable-mock#135]
Hi~ 最近的版本增加了个配置，获取路径报空指针，但我不清除具体是做什么的：
出错位置：
```java
    // FILE: com.alibaba.testable.agent.util.GlobalConfig:74
    public static void setupLogRootPath() {
        if (logFile == null) {
            String baseFolder = PathUtil.getFirstLevelFolder(System.getProperty(PROPERTY_USER_DIR),
                // 这里出错：Object.class.getResource("/") == null
                Object.class.getResource("/").getPath());
            if (!baseFolder.isEmpty()) {
                LogUtil.setGlobalLogPath(PathUtil.join(baseFolder, TESTABLE_AGENT_LOG));
            }
        } else if (!DISABLE_LOG_FILE.equals(logFile)) {
            LogUtil.setGlobalLogPath(PathUtil.join(System.getProperty(PROPERTY_USER_DIR), logFile));
        }
    }
```
错误信息：
```log
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NullPointerException
	at com.alibaba.testable.agent.util.GlobalConfig.setupLogRootPath(GlobalConfig.java:75)
	at com.alibaba.testable.agent.PreMain.premain(PreMain.java:32)
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
```
根据 #129 提示，改为 0.5.2 就没有问题。
配置问题如下 ：
```xml
    <properties>
        <java.version>11</java.version>
        <testable.version>0.6.2</testable.version>
        <!--<testable.version>0.5.2</testable.version>-->
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba.testable</groupId>
            <artifactId>testable-all</artifactId>
            <version>${testable.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <!-- Testable-mock -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>-javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
测试里什么也没写：
```java
// @SpringBootTest(classes = TestableMockTest.class)
public class TestableMockTest {

    @Test
    public void test() {
        System.out.println("==========start=============");
        System.out.println("========== end =============");
    }
}
```

**Comment by linfan** [comment]
通过`Object.class.getResource("/")`是希望获取存放构建产物的目录，以便自动适配Maven和Gradle的场景，但这种方法确实存在不严谨的地方，会在下个版本中修改。感谢指出~

**Comment by linfan** [comment]
已在`0.6.3`版本进行处理，升级试试看吧

**Comment by heyzqq** [comment]
> 已在 `0.6.3` 版本进行处理，升级试试看吧

可以了，太棒啦！
