### ISSUE TITLE
InvokeVerifier.verify NLP问题

### ISSUE THREAD

**Issue by forxfoo** [alibaba/testable-mock#140]
使用场景是 mock 被测试类两个私有方式，具体看代码

testableMock版本：0.5.2

```java
@EnablePrivateAccess(srcClass = StoreParser.class)
public class StoreParserTest {
    public static class Mock {
        @MockMethod(targetClass = Logger.class)
        public void warn(String msg) {
            System.out.println("[SOUT] warn: " + msg);
        }

        @MockMethod(targetClass = Logger.class)
        public void info(String msg) {
            System.out.println("[SOUT] info: " + msg);
        }

        @MockMethod(targetClass = Logger.class)
        public void error(String msg, Throwable t) {
            System.out.println("[SOUT] error: " + msg);
        }

        @MockMethod
        private void parseStore(StoreParser self, Store.Builder storeBuilder, StoreV1 storeV1) {
            System.out.println("mock parse store");
        }

        @MockMethod
        private void extractContainer(StoreParser self, Store.Builder storeBuilder, StoreV1 storeV1) {
            System.out.println("mock extract container");
        }
    }

    private StoreDao storeDao = Mockito.mock(StoreDao.class);

    @InjectMocks
    private StoreParser storeParser = new StoreParser();
    private StoreV1 storeV1;

    public StoreParserTest() {
        MockitoAnnotations.openMocks(this);
        storeV1 = new StoreV1();
        storeV1.setId(100);
    }

    @Nested
    class InsertTest {
        @Test
        @DisplayName("正常情况")
        public void test_normal() {
            doNothing().when(storeDao).update(any());
            storeParser.parse(storeV1);
            verify(storeDao, times(1)).update(any());
            InvokeVerifier.verify("parseStore").withTimes(1);
        }
    }
}

//被测试类 伪代码
public class StoreParser {
    public void parse(StoreV1 storeV1) {
        parseStore(storeBuilder, storeV1);
        extractContainer(storeBuilder, storeV1);
        storeDao.update(store);
    }
}
```

输出：

```
##这里 mock 是生效的，但在验证的时候报 NLP了，断点进去MockContextUtil.context.get()为 null
mock parse store
mock extract container
[SOUT] info: stores:100 elapsed:144 ms


java.lang.NullPointerException
	at com.alibaba.testable.core.matcher.InvokeVerifier.verify(InvokeVerifier.java:29)
	at com.zixun.superbrowser.adapter.parser.StoreParserTest$InsertTest.test_normal(StoreParserTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

**Comment by linfan** [comment]
对`@Nested`注解的情况目前没支持，会在近期版本里加上

**Comment by forxfoo** [comment]
辛苦辛苦  感谢感谢 这么好的测试框架 @linfan

**Comment by linfan** [comment]
`@Nested`注解已在`0.8.4`版本支持，感谢对`TestableMock`项目的关注
