### ISSUE TITLE
java-demo中DemoMockTest单元测试报错

### ISSUE THREAD

**Issue by hmlq** [alibaba/testable-mock#148]
报错内容如下：
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: com/alibaba/testable/core/util/LogUtil
	at com.alibaba.testable.agent.config.PropertiesParser.parseFile(PropertiesParser.java:37)
	at com.alibaba.testable.agent.PreMain.premain(PreMain.java:20)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.alibaba.testable.core.util.LogUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
FATAL ERROR in native method: processing of -javaagent failed

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by bigbigcarrot424** [comment]
我也遇到了这个问题,该怎么解决呢
