### ISSUE TITLE
项目集成testable后使用demo运行提示错误

### ISSUE THREAD

**Issue by Suny95** [alibaba/testable-mock#156]
使用版本：0.6.5
已确认项目中都已引用testable-all的依赖

```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: com/alibaba/testable/core/util/LogUtil
	at com.alibaba.testable.agent.config.PropertiesParser.parseFile(PropertiesParser.java:40)
	at com.alibaba.testable.agent.PreMain.premain(PreMain.java:20)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.alibaba.testable.core.util.LogUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more
FATAL ERROR in native method: processing of -javaagent failed
```

**Comment by linfan** [comment]
从错误来看是在运行的时候加载`com.alibaba.testable.core.util.LogUtil`类报了类型不存在，这个类是来自`testable-all`包中的。检查一下`testable-all`是否被加到了`< dependencyManagement>`区域，或者其他类似情况？
