### ISSUE TITLE
Mock运行时字节码报错java.lang.VerifyError: Bad type on operand stack in aaload

### ISSUE THREAD

**Issue by ss-superman** [alibaba/testable-mock#171]
报错异常：
![image](https://user-images.githubusercontent.com/16860171/121624013-52a5a700-caa3-11eb-925b-d4aac9ba9ce1.png)

`Connected to the target VM, address: '127.0.0.1:50948', transport: 'socket'
[INFO] TestableMock start at D:\Code\xxx\xxx

java.lang.VerifyError: Bad type on operand stack in aaload
Exception Details:
  Location:
    com/ctrip/hotel/dtl/suppliersettlement/domain/testablemock/FooBar.editDistance(Ljava/lang/String;Ljava/lang/String;)I @174: aaload
  Reason:
    Type 'com/ctrip/hotel/dtl/suppliersettlement/domain/testablemock/FooBarTest$Mock' (current frame, stack[6]) is not assignable to reference type
  Current Frame:
    bci: @174
    flags: { }
    locals: { 'com/ctrip/hotel/dtl/suppliersettlement/domain/testablemock/FooBar', 'java/lang/String', 'java/lang/String', integer, integer, '[[I', integer, integer }
    stack: { '[I', integer, 'com/ctrip/hotel/dtl/suppliersettlement/domain/testablemock/DistanceHelper', integer, integer, '[[I', 'com/ctrip/hotel/dtl/suppliersettlement/domain/testablemock/FooBarTest$Mock', integer }
  Bytecode:
    0x0000000: 2bb6 001a 3e2c b600 1a36 041d 0460 1504
    0x0000010: 0460 c500 1c02 3a05 0336 0615 061d a300
    0x0000020: 1219 0515 0632 0315 064f 8406 01a7 ffee
    0x0000030: 0336 0615 0615 04a3 0012 1905 0332 1506
    0x0000040: 1506 4f84 0601 a7ff ed04 3606 1506 1da3
    0x0000050: 0077 0436 0715 0715 04a3 0067 b800 222a
    0x0000060: b400 102b 2c15 0615 07b6 0026 9900 1a19
    0x0000070: 0515 0632 1507 1905 1506 0464 3215 0704
    0x0000080: 642e 4fa7 0037 1905 1506 3215 072a b400
    0x0000090: 1019 0515 0604 6432 1507 0464 2e19 0515
    0x00000a0: 0604 6432 1507 2e19 05b8 0022 1506 3215
    0x00000b0: 0704 642e b600 2a04 604f 8407 01a7 ff98
    0x00000c0: 8406 01a7 ff89 1905 1d32 1504 2eac     
  Stackmap Table:
    full_frame(@27,{Object[#2],Object[#22],Object[#22],Integer,Integer,Object[#28],Integer},{})
    chop_frame(@48,1)
    append_frame(@51,Integer)
    chop_frame(@73,1)
    append_frame(@76,Integer)
    append_frame(@85,Integer)
    same_frame(@134)
    same_frame(@186)
    chop_frame(@192,1)
    chop_frame(@198,1)

	at com.ctrip.hotel.dtl.suppliersettlement.domain.testablemock.FooBarTest.test_dis(FooBarTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)`

源代码如下：

被测试类：
`public class FooBar {

    private DistanceHelper helper = new DistanceHelper();

   // 编辑距离算法
    public int editDistance(String s1, String s2) {
        int m = s1.length();
        int n = s2.length();
        int[][] dp = new int[m + 1][n + 1];
        for (int i = 0; i <= m; i++) {
            dp[i][0] = i;
        }
        for (int j = 0; j <= n; j++) {
            dp[0][j] = j;
        }
        for (int i = 1; i <= m; i++) {
            for (int j = 1; j <= n; j++) {
                if (helper.isSameChar(s1, s2, i, j)) {
                    dp[i][j] = dp[i - 1][j - 1];
                } else {
                    dp[i][j] = helper.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]) + 1;
                }
            }
        }
        return dp[m][n];
    }
}`

// 帮助类（被Mock的对象）
`public class DistanceHelper {

    public boolean isSameChar(String s1, String s2, int i, int j) {
        return s1.charAt(i - 1) == s2.charAt(j - 1);
    }

    public int min(int a, int b, int c) {
        return Math.min(Math.min(a, b), c);
    }
}`

测试类
`import com.alibaba.testable.core.annotation.MockMethod;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class FooBarTest {

    public static class Mock {

        @MockMethod(targetClass = DistanceHelper.class)
        public boolean isSameChar(String s1, String s2, int i, int j) {
            return s1.charAt(i - 1) == s2.charAt(j - 1);
        }

        @MockMethod(targetClass = DistanceHelper.class)
        public int min(int a, int b, int c) {
            return Math.min(Math.min(a, b), c);
        }

    }

    @Test
    public void test_dis() {
        FooBar fooBar = new FooBar();
        int dis = fooBar.editDistance("bdef", "gefb");
        Assertions.assertEquals(dis, 3);
    }
}`

pom.xml：
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>TestableMockTest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <junit.version>5.6.2</junit.version>
        <testable.version>0.6.6</testable.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.alibaba.testable</groupId>
            <artifactId>testable-all</artifactId>
            <version>${testable.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>-javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>`

**Comment by linfan** [comment]
感谢详细的示例代码👍🏻
问题已复现，会尽快发布修复版本

**Comment by ss-superman** [comment]
> 感谢详细的示例代码👍🏻
> 问题已复现，会尽快发布修复版本

大佬能先解释下原因吗？想学习下TestableMock源码

**Comment by linfan** [comment]
修复已经提交到master分支了。

简单来说是计算字节码修改位置的时候，对参数有读取数组下标的情况处理有问题。
更具体一点的原因是对字节码的堆栈影响我们参考了[维基百科](https://en.wikipedia.org/wiki/Java_bytecode_instruction_listings)的这个表格，但事实证明里面对数组相关几个字节码的值好像不太对...

**Comment by linfan** [comment]
已发布`v0.6.7`版本，包含此修复

**Comment by ss-superman** [comment]
> 已发布`v0.6.7`版本，包含此修复

神速，点赞👍🏻
