### ISSUE TITLE
利用OmniConstructor.newInstance构造部分对象会报错Failed to invoke constructor

### ISSUE THREAD

**Issue by wh-upup** [alibaba/testable-mock#235]
多模块gradle项目,build.gradle参照如下配置

configurations {
    testableMock
    testImplementation.extendsFrom(testableMock)
}
dependencies {
    testableMock('com.alibaba.testable:testable-all:0.6.9')
    testAnnotationProcessor('com.alibaba.testable:testable-processor:0.6.9')
}
test {
    jvmArgs "-javaagent:${configurations.testableMock.find { it.name.contains("testable-agent") }.absolutePath}"
    useJUnitPlatform()
}
在src/test/resources/testable.properties中配置了omni.constructor.enhance.enable = true
在使用OmniConstructor.newInstance的时候一部分对象无法被构造，如下:
构造这种简单类型的对象
    String str = OmniConstructor.newInstance(String.class);能够成功
构造较为复杂对象
    NtpService ntpService = OmniConstructor.newInstance(NtpService.class);
会报错：com.alibaba.testable.core.exception.ClassConstructionException: Failed to invoke constructor
具体报错如下：
com.alibaba.testable.core.exception.ClassConstructionException: Failed to invoke constructor

	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:82)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:100)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:76)
	at com.alibaba.testable.core.tool.OmniConstructor.createInstance(OmniConstructor.java:241)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:94)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:76)
	at com.alibaba.testable.core.tool.OmniConstructor.createInstance(OmniConstructor.java:241)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:94)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:76)
	at com.alibaba.testable.core.tool.OmniConstructor.createInstance(OmniConstructor.java:241)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:94)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:76)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:33)
	at io.transwarp.manager.master.ntp.NtpServiceTest.configNtp(NtpServiceTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.testable.core.tool.OmniConstructor.createInstance(OmniConstructor.java:243)
	at com.alibaba.testable.core.tool.OmniConstructor.newObject(OmniConstructor.java:94)
	at com.alibaba.testable.core.tool.OmniConstructor.newInstance(OmniConstructor.java:76)
	... 78 more
Caused by: java.lang.NullPointerException: client cannot be null
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at org.apache.curator.framework.recipes.leader.LeaderLatch.<init>(LeaderLatch.java:148)
	at org.apache.curator.framework.recipes.leader.LeaderLatch.<init>(LeaderLatch.java:127)
	... 85 more
这种依赖配置下，感觉全局运行参数未生效

**Comment by linfan** [comment]
看起来是全局参数未生效，没有对类进行特殊构造处理，依然选择了类型自己的构造方法，同时构造方法里有参数不能为空的校验导致报错。

我这儿没有适合用来复现问题的现成代码，不太好验证。可以试试在子项目的resources目录也放一个testable.properties，配置omni.constructor.enhance.enable = true是否可行？

**Comment by linfan** [comment]
在curator项目的[LeaderLatch.java](https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java)文件里找到了导致报错的这行“client cannot be null”。

根本原因就是该类型的这行代码：

```
this.client = Preconditions.checkNotNull(client, "client cannot be null").newWatcherRemoveCuratorFramework();
```

由于被检查的`client`成员是一个接口类型，OmniConstructor会将它初始化为null，但这里检查了client不能为null，导致构建失败。通过添加`omni.constructor.enhance.enable = true`参数就能绕过这个问题。
