### ISSUE TITLE
 Illegal class name "" in class file- snappy-java

### ISSUE THREAD

**Issue by ddatsh** [alibaba/testable-mock#267]
testable-mock version: 0.7.4

```xml
<dependency>
    <groupId>org.xerial.snappy</groupId>
    <artifactId>snappy-java</artifactId>
    <version>1.1.8.4</version>
</dependency>
```
```java
@MockInvoke(targetClass = Snappy.class)
public static byte[] compress(byte[] var0) throws IOException {
	return null;
}
```

```java
Caused by: java.lang.ClassFormatError: Illegal class name "" in class file com/xxx/RedisSerializerSnappyTest$Mock
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredClasses0(Native Method)
	at java.lang.Class.getDeclaredClasses(Class.java:1867)
	at org.junit.platform.commons.util.ReflectionUtils.findNestedClasses(ReflectionUtils.java:1024)
	at org.junit.platform.commons.util.ReflectionUtils.findNestedClasses(ReflectionUtils.java:1009)
	at org.junit.platform.commons.support.ReflectionSupport.findNestedClasses(ReflectionSupport.java:333)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$toResolution$12(ClassSelectorResolver.java:138)
	at org.junit.platform.engine.support.discovery.SelectorResolver$Match.expand(SelectorResolver.java:646)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$enqueueAdditionalSelectors$1(EngineDiscoveryRequestResolution.java:109)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Collections$2.tryAdvance(Collections.java:4719)
	at java.util.Collections$2.forEachRemaining(Collections.java:4727)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.enqueueAdditionalSelectors(EngineDiscoveryRequestResolution.java:108)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:94)
```

**Comment by linfan** [comment]
尝试在项目中增加了snappy-java依赖，添加compress方法的Mock，同时在源码里调用了Snappy的compress方法，测试时能够正常进入Mock方法内，没有复现问题

**Comment by ddatsh** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.10</version>
    </parent>
    <groupId>com.demo</groupId>
    <artifactId>demo</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>2020.0.5</spring-cloud.version>
        <testable.version>0.7.4</testable.version>
        <jacoco.version>0.8.7</jacoco.version>
        <snappy.version>1.1.8.4</snappy.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.alibaba.testable</groupId>
            <artifactId>testable-all</artifactId>
            <version>${testable.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.7.21</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
            <version>1.1.8.4</version>
        </dependency>

    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <elastic.apm.enabled>false</elastic.apm.enabled>
                    </systemPropertyVariables>
                    <argLine>@{argLine}
                        -javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar=mockScope=associated
                    </argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <configuration>
                    <includes>
                        <include>com/**/*</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>pre-test</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>post-test</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-maven-plugin</artifactId>
                <version>1.18.20.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>delombok</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

```java

import cn.hutool.core.util.*;
import org.springframework.data.redis.serializer.*;
import org.springframework.util.SerializationUtils;
import org.xerial.snappy.*;

public class RedisSerializerSnappy implements RedisSerializer {

	@Override
	public Object deserialize(byte[] bytes) {

		if(null==bytes){

			return null;
		}

		return ObjectUtil.deserialize(decompress(bytes));
	}

	@Override
	public byte[] serialize(Object object) {

		return compress(SerializationUtils.serialize(object));
	}

	private byte[] compress(byte[] content) {

		try {

			return Snappy.compress(content);

		} catch (Exception e) {

			throw new SerializationException(e.getMessage(), e);
		}
	}

	private byte[] decompress(byte[] contentBytes) {

		try {

			return Snappy.uncompress(contentBytes);

		} catch (Exception e) {

			throw new SerializationException(e.getMessage(), e);
		}
	}
}
```

```java

import com.alibaba.testable.core.annotation.*;
import org.junit.jupiter.api.*;
import org.xerial.snappy.*;

import java.io.*;

public class RedisSerializerSnappyTest {

	RedisSerializerSnappy redisSerializerSnappy = new RedisSerializerSnappy();

	public static class Mock {

		@MockInvoke(targetClass = Snappy.class)
		public static byte[] compress(byte[] var0) throws IOException {

			return null;
		}
	}

	@Test
	public void test() {

		redisSerializerSnappy.serialize("");

	}
}
```
