### ISSUE TITLE
0.77版本静态方法mock不了

### ISSUE THREAD

**Issue by Juwairen2021** [alibaba/testable-mock#286]
其它mock都正常，唯独静态方法mock不了。
麻烦帮看看，谢谢。
[VERBOSE]    Mock method "getDefaultPictureUrl" as "com.xxx.yyy.common.utils.PlatformUtils::getDefaultPictureUrl() : java.lang.String"

	at com.xxx.yyy.common.dictionary.cache.ConfigManager.<clinit>(ConfigManager.java:19)
	at com.xxx.yyy.common.utils.PlatformUtils.getDefaultPictureUrl(PlatformUtils.java:615)

public class PlatformUtils {
    public static String getDefaultPictureUrl() {
        ConfigManager cm = ConfigManager.getInstance();
        ......

    	@MockInvoke(targetClass = PlatformUtils.class)
    	private String getDefaultPictureUrl(){
    		return "http://www.picurl";
    	}

**Comment by Juwairen2021** [comment]
maven多模块项目，PlatformUtils类在A模块，待测类XXXController在B模块
	private XXXController xxxController = new XXXController ();
        xxxController .myMethod();
