### ISSUE TITLE
单元测试不起作用

### ISSUE THREAD

**Issue by zhhui** [alibaba/testable-mock#67]
引入到现有的微服务项目中，总是走不到mock的方法。是不是依赖的juint jar有要求

**Comment by linfan** [comment]
不依赖测试框架哈，主流的任何测试框架或者版本都可以使用。
如果Mock不成功的话，可以先按照[自助问题排查](https://alibaba.github.io/testable-mock/#/zh-cn/doc/troubleshooting)文档快速定位一下原因。如果依然不可行，麻烦提供一下相关的测试代码，我们具体看一下。

**Comment by fisherng** [comment]
解决了吗？我遇到同样的问题，不生效啊

**Comment by linfan** [comment]
@fisherng 凭空不好查哈。可以提供一下你的使用方法，或者根据自助排查文档输出的结果，具体问题具体解决

**Comment by luyuanwan** [comment]
我也发现了mock方法不起作用 @zhhui

**Comment by linfan** [comment]
@luyuanwan 最好能提供一些细节信息，比如你是怎样使用然后发现没起作用的。估计是文档有些地方写得还不够清楚哈，但得知道是什么问题才好改正~

**Comment by asterisk622** [comment]
我也发现mock不起作用。

环境：
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
macOS 10.16

我的操作是把testable-mock中的 DemoMockTest.java   DemoMock.java 拷贝到自己的spring工程（2.1.6.RELEASE），去掉junit-jupiter-api的依赖，直接依赖原工程的junit(4.12) ，修改原来DemoMockTest的import，运行should_able_to_mock_member_method 就出下面错误。 

直接在idea中运行testable-mock中的相同方法，是成功的。

`objc[27179]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java (0x10725f4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1072dd4e0). One of the two will be used. Which one is undefined.
[DIAGNOSE] Handling test class com/alibaba/das/sqloptimize/slowsql/DemoMockTest
[DIAGNOSE]   Found 0 mock methods
[DIAGNOSE] Handling source class com/alibaba/das/sqloptimize/slowsql/DemoMock
[DIAGNOSE]   Handling method <init>
[VERBOSE]      Line 11, constructing "java/lang/Object" as "()V"
[DIAGNOSE]   Handling method outerFunc
[VERBOSE]      Line 16, constructing "java/lang/StringBuilder" as "()V"
[VERBOSE]      Line 16, invoking "append" as "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 16, invoking "innerFunc" as "(Ljava/lang/String;)Ljava/lang/String;"
[VERBOSE]      Line 16, invoking "append" as "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 16, invoking "staticFunc" as "()Ljava/lang/String;"
[VERBOSE]      Line 16, invoking "append" as "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 16, invoking "append" as "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 16, invoking "toString" as "()Ljava/lang/String;"
[DIAGNOSE]   Handling method commonFunc
[VERBOSE]      Line 23, constructing "java/lang/StringBuilder" as "()V"
[VERBOSE]      Line 23, invoking "trim" as "()Ljava/lang/String;"
[VERBOSE]      Line 23, invoking "append" as "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 23, invoking "append" as "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 23, invoking "substring" as "(II)Ljava/lang/String;"
[VERBOSE]      Line 23, invoking "append" as "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 23, invoking "append" as "(Ljava/lang/String;)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 23, invoking "startsWith" as "(Ljava/lang/String;)Z"
[VERBOSE]      Line 23, invoking "append" as "(Z)Ljava/lang/StringBuilder;"
[VERBOSE]      Line 23, invoking "toString" as "()Ljava/lang/String;"
[DIAGNOSE]   Handling method callerOne
[VERBOSE]      Line 30, invoking "callFromDifferentMethod" as "()Ljava/lang/String;"
[DIAGNOSE]   Handling method callerTwo
[VERBOSE]      Line 34, invoking "callFromDifferentMethod" as "()Ljava/lang/String;"
[DIAGNOSE]   Handling method staticFunc
[DIAGNOSE]   Handling method innerFunc
[VERBOSE]      Line 42, invoking "get" as "(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;"
[VERBOSE]      Line 42, invoking "readAllLines" as "(Ljava/nio/file/Path;)Ljava/util/List;"
[VERBOSE]      Line 42, invoking "stream" as "()Ljava/util/stream/Stream;"
[VERBOSE]      Line 42, invoking "joining" as "()Ljava/util/stream/Collector;"
[VERBOSE]      Line 42, invoking "collect" as "(Ljava/util/stream/Collector;)Ljava/lang/Object;"
[DIAGNOSE]   Handling method callFromDifferentMethod

java.nio.file.NoSuchFileException: /a-not-exist-file

	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.readAllLines(Files.java:3202)
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at com.alibaba.das.sqloptimize.slowsql.DemoMock.innerFunc(DemoMock.java:42)
	at com.alibaba.das.sqloptimize.slowsql.DemoMock.outerFunc(DemoMock.java:16)
	at com.alibaba.das.sqloptimize.slowsql.DemoMockTest.should_able_to_mock_member_method(DemoMockTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

`

**Comment by linfan** [comment]
已查证是由于主干代码已经采用了`0.5`版本代码示例，当前该版本尚未发布且包含不兼容的变更，导致按仓库中示例代码直接运行时无法识别Mock方法，将会在近期更新文档修复

**Comment by linfan** [comment]
`0.5.0`版本已发布🚀
