### ISSUE TITLE
java.lang.ClassFormatError: Illegal field modifiers in class 

### ISSUE THREAD

**Issue by shc-000** [alibaba/testable-mock#88]
你好，0.4.12版本，麻烦看下这个是什么原因导致的

[DIAGNOSE]   Found 1 mock methods
[DIAGNOSE] Handling source class ........
[DIAGNOSE]   Handling method addVersion
[DIAGNOSE]   Found 1 mock methods
[DIAGNOSE] Handling source class ........
[DIAGNOSE]   Handling method addVersion
[DIAGNOSE]   Found 1 mock methods
[DIAGNOSE] Handling source class .........
[DIAGNOSE]   Handling method addVersion
二月 09, 2021 8:47:16 上午 org.junit.platform.launcher.core.DefaultLauncher handleThrowable
警告: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.ClassFormatError: Illegal field modifiers in class ........ 0xA
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.junit.platform.commons.util.ReflectionUtils.getDefaultMethods(ReflectionUtils.java:1382)
	at org.junit.platform.commons.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:1355)
	at org.junit.platform.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:1297)
	at org.junit.platform.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:1281)
	at org.junit.platform.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:1267)
	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.findMethod(VintageTestDescriptor.java:167)
	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.toTestSource(VintageTestDescriptor.java:152)
	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.<init>(VintageTestDescriptor.java:56)
	at org.junit.vintage.engine.discovery.RunnerTestDescriptorPostProcessor.addChildrenRecursively(RunnerTestDescriptorPostProcessor.java:56)
	at org.junit.vintage.engine.discovery.RunnerTestDescriptorPostProcessor.applyFiltersAndCreateDescendants(RunnerTestDescriptorPostProcessor.java:39)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:48)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:62)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:177)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:164)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

[DIAGNOSE]   Found 1 mock methods
[DIAGNOSE] Handling source class .....
[DIAGNOSE]   Handling method addVersion

**Comment by linfan** [comment]
单从这个错误信息目前还定位不了问题，能否提供一下相关的代码

**Comment by linfan** [comment]
顶部的这段"Handling source class ........"是一直重复的在打印同一个Class吗？另外，有没有"Handling test class"的输出？

```
[DIAGNOSE] Found 1 mock methods
[DIAGNOSE] Handling source class ........
[DIAGNOSE] Handling method addVersion
[DIAGNOSE] Found 1 mock methods
[DIAGNOSE] Handling source class ........
[DIAGNOSE] Handling method addVersion
[DIAGNOSE] Found 1 mock methods
[DIAGNOSE] Handling source class .........
[DIAGNOSE] Handling method addVersion
```

**Comment by wqq-java** [comment]
遇到了同样的问题！！！
[DIAGNOSE] Handling test class xxxxServiceTest
[DIAGNOSE]   Found 1 mock methods
[DIAGNOSE] Handling source class xxxService
[DIAGNOSE]   Handling method getUserByUnified
[DIAGNOSE]   Handling method getUserNameById
[DIAGNOSE]   Handling method addAccount
[DIAGNOSE]   Handling method deleteAccount
[DIAGNOSE]   Handling method getUserAll
[DIAGNOSE]   Handling method updateStatus
[DIAGNOSE]   Handling method accountListWithoutAuth
[DIAGNOSE]   Handling method addAccountItoa
[DIAGNOSE]   Handling method updateRole
[DIAGNOSE]   Handling method currentLogin
[DIAGNOSE]   Handling method updateAccount

java.lang.ClassFormatError: Illegal field modifiers in class xxxxService: 0xA

**Comment by linfan** [comment]
从错误信息来看，是在加载类的时候遇到了非法的字段修饰符`0xA`。字节码`0xA`作为字段修饰符时候对应的值是`private`(0x2)+`static`(0x8)，是合法的字段修饰符`private static`，脱离上下文单从这个错误信息目前无法做进一步判断。猜测和`0.4.x`版本里自动将Mock方法改为`static`的机制有关，这种机制在`0.5`版本里已经移除，可以过几天新版本正式发布以后再试试看。

**Comment by linfan** [comment]
`0.5.0`版本已发布

**Comment by linfan** [comment]
issue先关闭了哈，如果这个问题还会发生，请reopen

**Comment by shower2019** [comment]
版本0.5.1也碰到了同样的错
[DIAGNOSE] Found 2 mock methods
[DIAGNOSE] Handling source class xx/xx/xx/xx/UserDetailBusiness
[DIAGNOSE] Handling method getUserDetail
[DIAGNOSE] Handling method getUserApps
java.lang.ClassFormatError: Illegal filed modifiers in class xx/xx/xx/xx/UserBusiness: 0xA
at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.junit.runners.model.TestClass.getSortedDeclaredFields(TestClass.java:77)
	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:70)
	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


UserBusiness是一个接口类，需要Mock的是实现类UserBusinessImpl中的两个方法，两个类里都没有找到private static修饰符

public interface UserBusiness{
       UserDto getUserDetail(UserIdVo userIdVo) throws BusinessException;
       List<Application> getUserApps(UserIdVo userIdVo) throws BusinessException;
}

**Comment by linfan** [comment]
@shower2019  感谢线索。
`TestableMock`会在被测类里动态增加一个`private static`的无用字段来标记这个类已经被处理过，当被测类恰好是接口的时候，在接口里定义`private static`字段就是非法的了。这个无用标记会在下个版本里去除掉。

**Comment by linfan** [comment]
这种情况其实是应该给包含实际代码调用的类型，比如上述的`UserBusinessImpl`类定义一个匹配的Mock类型，比如`UserBusinessImplMock`，用来置换其中的外部调用。接口类`UserBusiness`是不需要有Mock类的。

**Comment by shower2019** [comment]
@linfan 
感谢，测试类UserBusinessTest实际内容是对UserBusinessImpl的测试，只是之前用PowerMock习惯了这样命名。
现在将UserBusinessTest重命名为UserBusinessImplTest，可以规避这个错误。
并且测试类的目录结构看起来也需要严格按照被测代码来。比如放在business目录下不行，放在business/impl目录下就可以。

**Comment by linfan** [comment]
默认是在同名包下面寻找当前类关联的Mock类，除非显式的在测试类或被测类上加`@MockWith`注解，这种对应的目录结构的约束能避免Mock方法到处乱放，减少不必要的问题排查

**Comment by linfan** [comment]
`0.5.2`版本已发布，包含此问题的修复
